### ISSUE TITLE
Error executing task on Client

### ISSUE THREAD

**Issue by Mhowser** [NucleoidMC/DisguiseLib#1]
doing `/disguise PLAYERNAME as creeper` doesnt work. This error shows up in the game log 
```
Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 15 on entity class_746['Cosmocrat'/4563, l='ClientWorld minecraft:overworld', x=-322.50, y=64.00, z=1820.03]: old=265397(class java.lang.Integer), new=0(class java.lang.Byte)
	at Not Enough Crashes deobfuscated stack trace.(1.15.1+build.36)
	at net.minecraft.entity.data.DataTracker.copyToFrom(DataTracker:241)
	at net.minecraft.entity.data.DataTracker.writeUpdatedEntries(DataTracker:228)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onEntityTrackerUpdate(ClientPlayNetworkHandler:568)
	at net.minecraft.client.network.packet.EntityTrackerUpdateS2CPacket.apply(EntityTrackerUpdateS2CPacket:42)
	at net.minecraft.client.network.packet.EntityTrackerUpdateS2CPacket.apply(EntityTrackerUpdateS2CPacket:11)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
```

**Comment by samolego** [comment]
Hi, thanks for reporting! I'll have a look into it.
