### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by LambdAurora** [NucleoidMC/DisguiseLib#2]
tl;dr when a player collides with another player disguised as a falling block entity, it desyncs and the falling block entity starts gliding like it's on ice and occasionally it's position is reset, somehow the velocity does weird things.

other issue, quite a big console spam client-side about invalid packets:

```
[16:30:39] [main/FATAL] (Minecraft) Error executing task on Client
java.lang.IllegalStateException: Server tried to update attributes of a non-living entity (actually: FallingBlockEntity['Falling Block'/327, l='ClientLevel', x=49.12, y=65.00, z=49.20])
        at net.minecraft.client.network.ClientPlayNetworkHandler.onEntityAttributes(ClientPlayNetworkHandler.java:2198) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.network.packet.s2c.play.EntityAttributesS2CPacket.apply(EntityAttributesS2CPacket.java:73) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.network.packet.s2c.play.EntityAttributesS2CPacket.apply(EntityAttributesS2CPacket.java:17) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:21) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:144) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:118) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:103) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1015) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:215) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2@net.fabricmc.yarn.1_16_5.1.16.5+build.5-v2.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2@net.fabricmc.yarn.1_16_5.1.16.5+build.5-v2.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2@net.fabricmc.yarn.1_16_5.1.16.5+build.5-v2.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by samolego** [comment]
Thanks for reporting! The second one is a known issue (seems like #1 wasn't resolved after all).

First one seems really weird 😕  ...
